### ISSUE TITLE
[BUG] you dont filter Emojis

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Plus#4]
![image](https://user-images.githubusercontent.com/68120127/175787887-a5a7fed4-79b0-4233-940d-635be9c04b0c.png)
![image](https://user-images.githubusercontent.com/68120127/175787910-eecbba47-aab7-404c-8230-6d0e53b844f0.png)
> how to reproduce

Put emojis onto meower using ur emoji system

> expected

It shows up nowhere

> truth 

it shows up only on the HTML meower, making it so you can bypass filters

**Comment by showierdata9978** [comment]
possible fix: https://github.com/mathiasbynens/emoji-regex

**Comment by Bloctans** [comment]
transfer to meower vanilla?

**Comment by Bloctans** [comment]
also, i cant fix it 
![image](https://user-images.githubusercontent.com/93960460/175788898-9e1a1604-dbe3-421d-bdf8-065c1da5857b.png)

**Comment by Bloctans** [comment]
Closed as Cannot Fix
